### PR TITLE
Changes MC parameter from avoldot to avoldot0

### LINKED ISSUE #20: getsim() draws GIS variable instead of parameter
After the fix to #18, the Monte Carlo mode using `getsim()` and `runsim()` produces a new error:

> Cannot find parameter :avoldot in component ComponentPath(Symbol("##ModelDef#899"), :GISModel)
in eval at [base\boot.jl:370](https://github.com/openmodels/META-2021/issues/new#) 
in top-level scope at [deleteme\META-2021\src\repex.jl:48](https://github.com/openmodels/META-2021/issues/new#)
in runsim at [deleteme\META-2021\src\montecarlo.jl:224](https://github.com/openmodels/META-2021/issues/new#)
in var"#runsim#270" at [deleteme\META-2021\src\montecarlo.jl:230](https://github.com/openmodels/META-2021/issues/new#)
in set_param! at [Mimi\OClro\src\core\delegate.jl:54](https://github.com/openmodels/META-2021/issues/new#)
in #set_param!#222 at [Mimi\OClro\src\core\delegate.jl:55](https://github.com/openmodels/META-2021/issues/new#) 
in set_param! at [Mimi\OClro\src\core\defs.jl:515](https://github.com/openmodels/META-2021/issues/new#) 
in var"#set_param!#129" at [Mimi\OClro\src\core\defs.jl:518](https://github.com/openmodels/META-2021/issues/new#)
in kwcall at [Mimi\OClro\src\core\defs.jl:533](https://github.com/openmodels/META-2021/issues/new#)
in var"#set_param!#130" at [Mimi\OClro\src\core\defs.jl:537](https://github.com/openmodels/META-2021/issues/new#)
in error at [base\error.jl:35](https://github.com/openmodels/META-2021/issues/new#)

Here's a reproducible example using the example code for `runsim()` from the ReadMe but using `"Distribution"` instead of `"Nordhaus central value"` for the `gis_calib` function argument in `getsim():`

```
include("../src/MimiMETA.jl")
include("../src/montecarlo.jl")
model = full_model(rcp="RCP4.5", ssp="SSP2")
draws = getsim(100,
               "Kessler probabilistic", # PCF
               "Distribution", # AMAZ
               "Distribution", # GIS
               "Distribution", # WAIS
               "Distribution", # SAF
               false, # persit
               false, # emuc
               false) # prtp
results = runsim(model, draws,
                 true, # ism_used
                 true, # omh_used
                 true, # amoc_used
                 true, # saf_used
                 "Cai et al. central value", # AMAZ
                 "Distribution") # WAIS
```

The issue is that `getsim()` produces a draw with column name `GISModel_avoldot`, which is a variable in `GIS.jl`, not a parameter. Probably the error did not come up before because the parameter was not correctly updated with Monte Carlo draws (see #18). The name of the actual parameter is `avoldot0`. Since `vv.avoldot = pp.avoldot0 * pp.meltmult` (`GIS.jl`, l. 28) and `pp.meltmult` only takes values of one (see `data/GISparams.csv`), a simple fix in `getsim()` seems changing the name from `GISModel_avoldot` to `GISModel_avoldot0`.

But I'm not 100% sure this is compatible with non-Nordhaus specifications of the GIS component (`Robinson` and `Non-linear equilibrium function`)

### PR DESCRIPTION
**Pull request by jrising**
Resolves #20 .

### CODE REVIEW

**Comment by jrising** [comment]
Tested it, and the fix resolves the error.

**Comment by pwaidelich** [comment]
@jrising Do you need any more input/info on this from me?

**Comment by jrising** [comment]
@pwaidelich Only if you want to test it on your end. Otherwise, I'll merge this in and close the issue.

**Comment by jrising** [comment]
Thanks for checking!

**Pull request merged**
